(function(){
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const languageLabel={'yue-HK':'粤语','zh-CN':'普通话','en-US':'English'};
  const notice=sessionStorage.getItem('iot-user-notice');
  if(notice){sessionStorage.removeItem('iot-user-notice');const box=document.createElement('div');box.setAttribute('role','status');box.textContent=notice;Object.assign(box.style,{position:'fixed',bottom:'20px',right:'20px',padding:'16px',background:'#243047',color:'white',zIndex:'100'});document.body.append(box);setTimeout(()=>box.remove(),6000);}
  const emotionLabel={positive:'正向',neutral:'平稳',negative:'需关注'};
  const deviceStatusLabel={online:'在线',stale:'心跳延迟',offline:'离线'};
  let allDevices=[],deviceFilter='all';
  const deviceFilters={all:()=>true,esp:d=>String(d.transport||'').startsWith('esp'),sim:d=>Number(d.is_simulator)===1||d.transport==='simulator',online:d=>d.status==='online'};
  function applyAdminProfile(){const name=localStorage.getItem('iot-admin-nickname')?.trim()||'管理员';const avatar=localStorage.getItem('iot-admin-avatar');const nameEl=$('topbar-username'),avatarEl=$('topbar-avatar');if(nameEl)nameEl.textContent=name;if(!avatarEl)return;if(avatar){avatarEl.textContent='';avatarEl.style.backgroundImage=`url("${avatar}")`;avatarEl.style.backgroundSize='cover';avatarEl.style.backgroundPosition='center';avatarEl.classList.add('has-image');}else{avatarEl.textContent='管';avatarEl.style.backgroundImage='';avatarEl.classList.remove('has-image');}}
  function metadata(row){try{return JSON.parse(row.metadata_json||'{}')}catch{return {}}}
  async function get(path){const res=await fetch(path,{cache:'no-store'});if(!res.ok)throw new Error(`${res.status}`);return res.json()}
  function renderEmotions(counts){const total=Object.values(counts||{}).reduce((a,b)=>a+b,0);if(!total){$('emotion-bars').innerHTML='<div class="empty-state">等待情绪资料</div>';return}$('emotion-bars').innerHTML=Object.entries(counts).map(([emotion,count])=>`<div class="bar-row"><span>${emotionLabel[emotion]||esc(emotion)}</span><div class="bar-track"><div class="bar-fill ${esc(emotion)}" style="width:${Math.max(4,count/total*100)}%"></div></div><strong>${count}</strong></div>`).join('')}
  function renderDevices(){const rows=allDevices.filter(deviceFilters[deviceFilter]||deviceFilters.all);if(!rows.length){$('device-list').innerHTML='<div class="empty-state">尚无设备接入 → 前往「设备接入」按向导配置</div>';return}$('device-list').innerHTML=rows.map(d=>{const isEsp=String(d.transport||'').startsWith('esp');const badge=isEsp?'<span class="device-badge esp">ESP</span>':'<span class="device-badge sim">模拟器</span>';const meta=[d.firmware_version||d.firmware||'firmware 未提供',d.protocol_version==null?null:'协议 v'+d.protocol_version,d.board_model||null].filter(Boolean).join(' · ');return `<div class="device-row ${isEsp?'esp':''}"><div><div class="device-name"><a class="device-link" href="/dashboard/device/${encodeURIComponent(d.device_id)}">${esc(d.device_id)}</a>${badge}</div><div class="device-meta">${esc(meta)} · 最后心跳 ${d.last_seen?new Date(d.last_seen*1000).toLocaleTimeString():'—'}</div></div><span class="device-status ${esc(d.status)}">${esc(deviceStatusLabel[d.status]||d.status_label||d.status)}</span></div>`}).join('')}
  function renderEspStatus(esp){if(!esp){['esp-status','ota-status','opus-status','lan-status'].forEach(id=>{if($(id))$(id).textContent='无法检查'});return}const settings=esp.settings||{},network=esp.network||{},opus=esp.opus||{};if($('esp-status'))$('esp-status').textContent=settings.enabled?'监听中':'未启用';if($('ota-status'))$('ota-status').textContent=settings.ota_enabled?`已启用 · ${network.firmware_count??0} 个固件`:'未启用';if($('opus-status')){$('opus-status').textContent=opus.available?'可用':'不可用';$('opus-status').className=opus.available?'':'muted'}if($('lan-status'))$('lan-status').textContent=(network.addresses||[]).length?network.addresses[0]:'无局域网地址'}
  function renderRows(rows){if(!rows?.length){$('conversation-rows').innerHTML='<tr><td colspan="6" class="empty-state">等待对话资料</td></tr>';return}$('conversation-rows').innerHTML=rows.slice(0,30).map(r=>{const m=metadata(r);return `<tr><td>${new Date(r.created_at*1000).toLocaleString()}</td><td>${esc(r.user_id)}<br><small>${esc(m.device_id||'—')}</small></td><td><span class="emotion-pill ${esc(r.emotion)}">${emotionLabel[r.emotion]||esc(r.emotion)}</span></td><td>${esc(r.input_text)}</td><td>${esc(r.response_text)}</td><td>${esc(m.model||'—')}</td></tr>`}).join('')}
  function renderUsers(payload){const users=payload?.items||[];if(!users.length){$('user-list').innerHTML='<div class="empty-state">尚未登记用户</div>';return}$('user-list').innerHTML=users.map(u=>`<a class="user-row" href="/dashboard/user/${encodeURIComponent(u.user_id)}"><div><strong>${esc(u.display_name||u.user_id)}</strong><small>${esc(u.gender||'不透露')} · ${u.age_at_registration==null?'年龄未提供':esc(u.age_at_registration+' 岁')} · ${esc(languageLabel[u.preferred_language]||u.preferred_language||"未设定")}</small></div><span class="device-status ${u.status==='active'?'online':'offline'}">${u.status==='active'?'启用':'停用'}</span></a>`).join('')}
  async function load(){try{const [health,summary,devices,rows,users,esp]=await Promise.all([get('/health'),get('/api/dashboard/summary'),get('/api/devices'),get('/api/conversations'),get('/api/users'),get('/api/esp/status').catch(()=>null)]);const counts=summary.emotion_distribution||{};const deviceCounts=summary.device_counts||{};$('service-status').textContent='服务正常';$('service-status').className='status-badge ok';$('llm-status').textContent=health.deepseek_configured?'已配置':'Fallback 模式';$('conversation-count').textContent=summary.conversation_count??rows.length;$('user-count').textContent=summary.active_user_count??users.total??0;$('online-count').textContent=deviceCounts.online??0;$('device-summary').textContent=`${deviceCounts.stale??0} stale · ${deviceCounts.offline??0} offline`;$('latency').textContent=summary.average_latency_ms!=null?`${summary.average_latency_ms} ms`:'—';renderEmotions(counts);allDevices=Array.isArray(devices)?devices:[];renderDevices();renderRows(rows);renderUsers(users);renderEspStatus(esp)}catch(err){$('service-status').textContent='服务连接中断';$('service-status').className='status-badge error';$('llm-status').textContent='无法检查'}}
  $('device-filter')?.addEventListener('click',event=>{const value=event.target.getAttribute&&event.target.getAttribute('data-filter');if(!value)return;deviceFilter=value;Array.prototype.forEach.call($('device-filter').children,button=>button.classList.toggle('on',button===event.target));renderDevices()});
  $('refresh-btn').addEventListener('click',load);$('new-user-btn')?.addEventListener('click',()=>{window.location.href='/simulator'});window.addEventListener('iot:authenticated',load);window.addEventListener('iot:admin-profile-updated',applyAdminProfile);applyAdminProfile();load();setInterval(load,5000);
})();
