(function(){
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const languageLabel={'yue-HK':'粵語','zh-CN':'普通話','en-US':'English'};
  const notice=sessionStorage.getItem('iot-user-notice');
  if(notice){sessionStorage.removeItem('iot-user-notice');const box=document.createElement('div');box.setAttribute('role','status');box.textContent=notice;Object.assign(box.style,{position:'fixed',bottom:'20px',right:'20px',padding:'16px',background:'#243047',color:'white',zIndex:'100'});document.body.append(box);setTimeout(()=>box.remove(),6000);}
  const emotionLabel={positive:'正向',neutral:'平穩',negative:'需關注'};
  function metadata(row){try{return JSON.parse(row.metadata_json||'{}')}catch{return {}}}
  async function get(path){const res=await fetch(path,{cache:'no-store'});if(!res.ok)throw new Error(`${res.status}`);return res.json()}
  function renderEmotions(counts){const total=Object.values(counts||{}).reduce((a,b)=>a+b,0);if(!total){$('emotion-bars').innerHTML='<div class="empty-state">等待情緒資料</div>';return}$('emotion-bars').innerHTML=Object.entries(counts).map(([emotion,count])=>`<div class="bar-row"><span>${emotionLabel[emotion]||esc(emotion)}</span><div class="bar-track"><div class="bar-fill ${esc(emotion)}" style="width:${Math.max(4,count/total*100)}%"></div></div><strong>${count}</strong></div>`).join('')}
  function renderDevices(devices){if(!devices?.length){$('device-list').innerHTML='<div class="empty-state">等待 ESP 或 simulator 上報</div>';return}$('device-list').innerHTML=devices.map(d=>`<div class="device-row"><div><div class="device-name">${esc(d.device_id)}</div><div class="device-meta">${esc(d.firmware_version||'firmware 未提供')} · 最後心跳 ${d.last_seen?new Date(d.last_seen*1000).toLocaleTimeString():'—'}</div></div><span class="device-status ${esc(d.status)}">${esc(d.status_label||d.status)}</span></div>`).join('')}
  function renderRows(rows){if(!rows?.length){$('conversation-rows').innerHTML='<tr><td colspan="6" class="empty-state">等待對話資料</td></tr>';return}$('conversation-rows').innerHTML=rows.slice(0,30).map(r=>{const m=metadata(r);return `<tr><td>${new Date(r.created_at*1000).toLocaleString()}</td><td>${esc(r.user_id)}<br><small>${esc(m.device_id||'—')}</small></td><td><span class="emotion-pill ${esc(r.emotion)}">${emotionLabel[r.emotion]||esc(r.emotion)}</span></td><td>${esc(r.input_text)}</td><td>${esc(r.response_text)}</td><td>${esc(m.model||'—')}</td></tr>`}).join('')}
  function renderUsers(payload){const users=payload?.items||[];if(!users.length){$('user-list').innerHTML='<div class="empty-state">尚未登記使用者</div>';return}$('user-list').innerHTML=users.map(u=>`<a class="user-row" href="/dashboard/user/${encodeURIComponent(u.user_id)}"><div><strong>${esc(u.display_name||u.user_id)}</strong><small>${esc(u.gender||'不透露')} · ${u.age_at_registration==null?'年齡未提供':esc(u.age_at_registration+' 歲')} · ${esc(languageLabel[u.preferred_language]||u.preferred_language||"未設定")}</small></div><span class="device-status ${u.status==='active'?'online':'offline'}">${u.status==='active'?'啟用':'停用'}</span></a>`).join('')}
  async function load(){try{const [health,summary,devices,rows,users]=await Promise.all([get('/health'),get('/api/dashboard/summary'),get('/api/devices'),get('/api/conversations'),get('/api/users')]);const counts=summary.emotion_distribution||{};const deviceCounts=summary.device_counts||{};$('service-status').textContent='服務正常';$('service-status').className='status-badge ok';$('llm-status').textContent=health.deepseek_configured?'已配置':'Fallback 模式';$('conversation-count').textContent=summary.conversation_count??rows.length;$('user-count').textContent=summary.active_user_count??users.total??0;$('online-count').textContent=deviceCounts.online??0;$('device-summary').textContent=`${deviceCounts.stale??0} stale · ${deviceCounts.offline??0} offline`;$('latency').textContent=summary.average_latency_ms!=null?`${summary.average_latency_ms} ms`:'—';renderEmotions(counts);renderDevices(devices);renderRows(rows);renderUsers(users)}catch(err){$('service-status').textContent='服務連線中斷';$('service-status').className='status-badge error';$('llm-status').textContent='無法檢查'}}
  $('refresh-btn').addEventListener('click',load);$('new-user-btn')?.addEventListener('click',()=>{window.location.href='/simulator'});load();setInterval(load,5000);
})();
